<?php

namespace DoctrineProxy\__CG__\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OfertaLaboral extends \Entity\OfertaLaboral implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'fecha_publicacion', 'descripcion', 'requisitos', 'ubicacion', 'beneficios', 'visibilidad', 'postulaciones');
        }

        return array('__isInitialized__', 'id', 'fecha_publicacion', 'descripcion', 'requisitos', 'ubicacion', 'beneficios', 'visibilidad', 'postulaciones');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OfertaLaboral $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaPublicacion($fechaPublicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaPublicacion', array($fechaPublicacion));

        return parent::setFechaPublicacion($fechaPublicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaPublicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaPublicacion', array());

        return parent::getFechaPublicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescripcion($descripcion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescripcion', array($descripcion));

        return parent::setDescripcion($descripcion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescripcion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescripcion', array());

        return parent::getDescripcion();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequisitos($requisitos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequisitos', array($requisitos));

        return parent::setRequisitos($requisitos);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequisitos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequisitos', array());

        return parent::getRequisitos();
    }

    /**
     * {@inheritDoc}
     */
    public function setUbicacion($ubicacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUbicacion', array($ubicacion));

        return parent::setUbicacion($ubicacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getUbicacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUbicacion', array());

        return parent::getUbicacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setBeneficios($beneficios)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBeneficios', array($beneficios));

        return parent::setBeneficios($beneficios);
    }

    /**
     * {@inheritDoc}
     */
    public function getBeneficios()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBeneficios', array());

        return parent::getBeneficios();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisibilidad($visibilidad)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisibilidad', array($visibilidad));

        return parent::setVisibilidad($visibilidad);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisibilidad()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisibilidad', array());

        return parent::getVisibilidad();
    }

    /**
     * {@inheritDoc}
     */
    public function addPostulacione(\Entity\Postulacion $postulaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPostulacione', array($postulaciones));

        return parent::addPostulacione($postulaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function removePostulacione(\Entity\Postulacion $postulaciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePostulacione', array($postulaciones));

        return parent::removePostulacione($postulaciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostulaciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostulaciones', array());

        return parent::getPostulaciones();
    }

}
